
# Configuration file for "weatherserviceintegration"
# 
# This file contains configuration values for configurable variables in your Ballerina code.
# Both package-specific and imported module configurations are included below.
# 
# Learn more about configurable variables:
# https://ballerina.io/learn/provide-values-to-configurable-variables/#provide-via-toml-syntax
#
# Note: This file is automatically added to .gitignore to protect sensitive information. 

weatherApiKey = "cb1d5b2bc7fe84074f0930f8b184d6b3"	# Type of STRING

